# When expressed in NumPy, it becomes as follows

In [1]:

import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

# [Problem 1] Matrix product is calculated manually

For matrix multiplication, the number of columns in the first matrix must be equal to the number of rows in the second matrix. The result matrix has the number of rows of the first and the number of columns of the second matrix.

### The Calculation process is  explain in markdown text

$$A =\begin{bmatrix}-1, & 2, & 3\\4, & -5, & 6\\7, & 8, & -9\end{bmatrix}$$,

$$B =\begin{bmatrix}0, & 2, & 1\\0, & 2, & -8\\2, & 9, & -1\end{bmatrix}$$,

$$AB =\begin{bmatrix}0+0+6, & -2+4+27, &-1+(-16)+(-3)\\0+0+12, & 8+(-10)+54, & 4+40+(-6)\\0+0+(-18), & 14+16+(-81), & 7+(-64)+(-9)\end{bmatrix}$$,

$$AB =\begin{bmatrix}6, & 29, & -20\\12, & 52, & 38\\-18, & -51, & -48\end {bmatrix}$$

# [Problem 2] Calculation by NumPy function

This matrix product of NumPy can be easily calculated using np.matmul()

In [7]:
import  numpy  as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
np.matmul(a_ndarray,b_ndarray)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

# [Problem 3] Implementation of calculation of a certain element

In [8]:

print(f'The calculation of 0th row of matrix A and the 0th column of matrix B is:',a_ndarray[0,0] * b_ndarray[0,0] + a_ndarray[0,1] *b_ndarray[1,0] + a_ndarray[0,2] *b_ndarray[2,0])

The calculation of 0th row of matrix A and the 0th column of matrix B is: 6


# [Problem 4] Creating a function that performs matrix multiplication

In [9]:
import numpy as np
def matrix_multiplication(matrix_A, matrix_B):
    matrix = np.zeros(9)
    product = matrix.reshape(3, 3)
   
    for x in range(len(matrix_A)):
        for y in range(len(matrix_B[0])):
            for z in range(len(matrix_B)):
                product[x][y] += matrix_A[x][z] * matrix_B[z][y]
    print(product)
matrix_multiplication(a_ndarray, b_ndarray)

[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]


# [Problem 5] Judge the input whose calculation is not defined

In [7]:
d_ndarray_ = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

In [12]:
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

if d_ndarray.shape[0] == e_ndarray.shape[1]:
    print(product_of_matrix(d_ndarray, e_ndarray))
else:
    print("Sorry! the following matrices are not aligned!")

Sorry! the following matrices are not aligned!


# [Problem 6] Transposition

Transposing one matrix allows you to calculate the matrix product.

to do this we use the np.transpose() or .T attributes and calculate the matrix product.

In [ ]:
print('The product of the matrix when transposing matrix a is: ')
np.dot(a_ndarray.T,b_ndarray)

The product of the matrix when transposing matrix a is: 


array([[ 14,  69, -40],
       [ 16,  66,  34],
       [-18, -63, -36]])

James M Bockarie